discord:
  enabled: false
  webhooks:
    - username: "ip change notifier"
      url: "URL HERE"
      prefix_header: 0
      bold: false
      ping: "@here"
    
    - username: "ip change notifier"
      url: "URL HERE"
      prefix_header: 1
      bold: true
      #ping: "@everyone"

smptp:
  enabled: false
  #TODO add the rest of the smptp stuff
  